name: untitled8
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6
  firebase_core: 3.15.2
  firebase_auth: 5.7.0
  cloud_firestore: 5.6.12
  url_launcher: 6.2.6
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^21.1.35
  docx_to_text: ^1.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
